<<<
== Execution

An alternative system, even if it’s perfect, is no good to anyone without some means of getting there.  In some ways, this is associations strongest point, as it has unique properties relative to other means of organizing society.  Specifically, an association is a profit seeking enterprise.  In fact, if the size of modern governments is any indication, it may very well be the most profitable industry in human history.

Given that the motivation for creating and joining associations is pragmatic rather that ideological, it does not actually require anyone to buy in to some particular philosophy.  In fact, once the first association is profitable, the prospect of new sources of revenue will motivate additional firms to join the market, without the need for any special effort whatsoever.  Once this happens the state will quickly become obsolete, especially since it is likely forming a new association will not require significant capital.

The only major obstacle is the question of how to start that first association.  It is, in many ways, a problem with a simple solution, namely, you just need employees and customers, although given the novelty of the industry there are a great many details that will need to be worked out, and many concerns which will need to be accounted for.

To start, however, let us suppose you are a regular person, who is interested in creating a world of associations.  How can you help bring that about?  First, you can popularize the idea.  Familiarize yourself with the concepts so you can explain them to potential associates.  In a sense, become a part of the viral marketing campaign for the as of yet non-existent first association.

Second, even if an association as a business doesn’t exist, association as a way of life does.  Find other people and organize, collaborate, meet online, meet in person, throw events, and more.  Basically, start living like you’re already an associate however you can, and who knows, that club you start could very well grow into a lucrative enterprise in the near future.

As a final suggestion for my fellow normies, even if you aren’t interested in being an association early adopter, is to make it very clear you will not abide violence against associates (specifically by your government).  There will be a tremendous temptation for old world elites to crush this before it gets out of hand, and that will certainly not make this any easier.

Now, that’s all well and good for building up the customer base, but nothing goes anywhere without people actually digging in and building the thing.  This, obviously, will require drive, creativity, ambition, vision, and perhaps a healthy dose of greed.  In short, it will require entrepreneurs.  To you I can only suggest a loose framework for a plan.

The above three points for regular people apply, of course, but for you I think a good first step will be to create a non-profit foundation who’s stated purpose is to incorporate the first association, to found the PSA Council, and to popularize the concept of associations.  It would, I suspect, be beneficial for this foundation to be made up of ideological associates, though perhaps unnecessary.

Although it may be possible for the Foundation to execute its mission on a paltry budget, I imagine that some amount of financing will be helpful.  There are many causes and organizations who may be interested in donating, some obvious, like libertarians and anarchists.  It may also be worth exploring interest in religious communities.  Muslims, in particular, may find the possibility of creating Sharia compliant associations very intriguing.

Once the Foundation is founded and funded, the rest of this technically becomes a great big helping of not my problem.  Nevertheless, I will offer my understanding of where to go from there.

From how I see it, there are three possibilities/strategies available (broadly defined), and they all depend on how agreeable old world elites are (I have a suggestion on how they can be made more agreeable).  Let’s call these three options (in order of increasing difficulty), Association in Place, Association in Obscurity, and Association in Defiance.

The easiest case by far is Association in Place.  Basically, you find some sympathetic country who agrees with your vision, you design some protocol for associate v. citizen disputes, and then you start taking in customers.  After that, it’s just a matter of running your business.  Once you’ve worked the kinks out (i.e. start turning a profit), other firms will join in, and congratulations, you’ve killed the state, go throw a party.

For that hypothetical hero nation, I have an idea that should help you sunset elegantly, specifically with regards to your currency.  Basically, when it’s time to shutter your doors, you can auction off all your land and assets for the old money.  This way the currency will retain some value until the very last day, which will help with taking care of your employees.  You can also use it to “buy” retirement investments for all your pensioners/etc., so they aren’t screwed over by the transition.

At the midpoint in difficulty we find Association in Obscurity.  Put simply, in this case, you find a decent chunk of land somewhere, where the nation who technically owns it is either too weak, too indifferent, or too sympathetic to complain when you start building a city there but not paying taxes (or hey, maybe they’re just too bribed, lol).

This is certainly a slower way to do it, and will require a reasonably large number of highly motivated people, at least to start.  Once you start getting farms and factories and such, things should start to snowball.  With associations proven to work, it becomes a much easier sell to the masses, and if you can offer them lower “governance” expenses and better service (which shouldn’t be too hard, tbh), your problem might be too many eager customers, rather than too few.

You may have some problems with old world bullshit trying to tear you down at this point, though the solution here is likely similar to how Association in Defiance will work, but even easier.  I’ll cover that in a bit, but for here I’ll just note that this is a ‘future you’ problem, and when (or if) it comes, you should have much better tools at your disposal than a few suggestions from some nobody.

Anyway, let’s cover the last scenario, Association in Defiance.  This one is very similar to the last, but with (as you might have guessed), more defiance.  This is certainly the most difficult possibility, and the one most likely to contain violence.  You would pick your chunk of land, but this time more based on your ability to make the country you’re taking it from bleed if they take up arms against you than on the odds of them leaving you alone.

You would then populate this land with the most belligerent and well armed people you can find, and make it clear that if that nation goes to war against you, you are perfectly capable of (and willing to) burn the old wold to the ground and build the new one on top of it.  This is (obviously) a situation we would like to avoid, and thankfully you actually have access to a secret weapon, though I’ll cover that a bit later, as it applies more generally as well.

Anyway, after you’ve got your association made and functional, the process is much the same as above.  Expand operations, find customers, build systems, try not to die.

I am going to cover the war/army problem in its own section, but I will include here the aforementioned suggestion for making elites more agreeable (which is another one of your secret weapons).  You see, there’s an interesting fact about the state that is so obvious and trivial it can be overlooked, specifically, it’s made out of people.  Associations will be the death of the state, but all the rich and powerful people who run it are perfectly capable of being rich and powerful associates.

If you can properly incentivize those elites, then the state will follow.  My suggested offer is a simple one.  The government has done many bad things (like drone striking children), and in associations the responsibility for those choices can only be assigned to people, not to fictions of law (on accounts of there not being any law in the first place).  Put another way, the members and influencers of many states have blood on their hands, and every scrap of their wealth couldn’t even begin to set things right.

Given this, the natural fate of old world elites under associations is poverty at best.  However, it is of far greater value to destroy state power itself than it is to chase notions of justice against the parties who wielded it.  In order to bring about the new world peacefully, you can offer these elites unlimited clemency for actions of the state taken prior to the creation of associations.  This way, they keep their wealth and influence, and honestly, all it costs them is not having to worry about getting murdered by their fellow gangsters.

If no one wields state power (aka, institutionalized violence), then no one can wield it against you.  Even without the offer of clemency, associations would be a net benefit to them.
