<<<
== The War Problem

Possibly the greatest risk of transitioning into an associated world will be elements from the old world taking their giant armies and trying to stop it.  I believe that this plan could survive the attempt, but even if I could guarantee it I would still prefer to avoid that situation.

Technically, given that I cannot explode things with my mind and wholly lack the charisma to lead an army, this is not a me problem.  Nevertheless, it is important enough that I will offer some thoughts on the matter.

The first and best option is to simply secure the permission of the old world to replace it, as I mentioned elsewhere.  If that does not work out, then things get more complicated.

Associations, not naturally inclined to violence, are unlikely to be able to afford much in the way of military hardware, and would prefer not to regardless.  A military is not an easy thing to make money with.  Technically speaking, this is a feature, but very real armies exist right now, so we can’t ignore it.

The obvious solution is to amass a large quantity of (relatively) cheap and effective weapons, and to deploy them in such a way that it is clear any aggression against an associate will end disastrously for the aggressor.  To finance this, one could include a provision in the PSA Council that any member association must provide some quantity of funds.

There is merit to this idea, certainly, though it also has some obvious problems.  The biggest of which is that you will have created an organization with a lot of military hardware.  Even if it is intended to shut down as the old world drains away, and you have plans for how, there will be a lot of people with a motivation to keep it going as long as possible.  In fact, they may very well be motivated to keep it going indefinitely, and then whoops, it’s the state again.

Still, this plan may be necessary to some extent, so I can offer a few mitigations.  For starters, it should (perhaps paradoxically), be designed wholly for maximum offense and destruction.  The reason for this is a) its purpose is to discourage hostile action, and b) if it goes out of control, the worse it is at defense, the easier it will be for a motley crew of rebels to take it down.

It should also employ as few people as possible, and they should be pretty widely distributed geographically so that if they act out of line, other associates and their security firms will have easy access.  Also, obviously, these employees should have very big stakes (in a staking association), and should not be allowed to cluster in any particular association.

Another strategy, that works for both controlling your hypothetical army and discouraging the real ones from invading, is for every associate to be well armed and belligerent.  The absence of any kind of gun control may naturally lead to the first, but it may nevertheless be worthwhile to encode, temporarily, a militia requirement in the PSA Council.  If every associate is armed, trained, and angry, it may simply be untenable for any nation to invade, no matter how desperately they want to.

The final suggestion I have is quiet possibly the best one, and it’s the secret weapon I alluded to elsewhere.  You see, there’s a funny property about an associations.  It isn’t a country.  It has none of the baggage of being one, and in fact by its very nature will want as many customers as possible.  There is also an equally funny little property about armies, because, wouldn’t you know, they are made out of people.

There is no particular reason, from an association’s point of view, to not simply “bribe” an invading army out from under itself.  And the best part is, this isn’t even an expense, it’s an investment.  They don’t even need to fight for your cause, just have something productive to do that appeals to them (and then live long enough to pay plenty of dues).  Associations, especially early ones, will by the nature of their situation need a tremendous capacity to onboard new members (distributed amongst all of them), because there will be so many potential new associates, and most firms won’t want to leave money on the table for their competition.

This, especially combined with the other strategies, gives associates the ability to make a very temping offer to any would be conquerers.  You can join us and get a real job (and maybe some great perks), or you can die to maybe make some jackass in your home country a bit richer.  If things are happening fast enough, they might not even need to move out.

Another fun fact, our little secret weapon up there will exist forever, which means that any hypothetical attempts at recreating the state by force of arms will have a nigh impossible barrier.  Technically, this could even work in the rogue army scenario presented in the first solution, although it might still be a bit of a chore… or maybe just an embarrassment, now that I think about it.
