<<<
== The Nukes

Although I don’t have many thoughts or suggestions on the subject, I nevertheless feel it is important enough to at least address.

If there were never any nuclear weapons on earth, then with associations there would be little incentive to develop them (given how expensive they are).  Unfortunately, they already exist, and when the old world fades the bombs will still be there.  It won’t be particularly easy during the fade either.

As for their ultimate fate, the weapons can likely be recycled to generate electricity, so in the long term it won’t be too much of a problem (until it becomes one again, though I’ll touch on that later).  In the short term, however, some plan will be required.  If possible, it might be best to simply pick a nuclear armed country to hire as a nuclear shield, presumably the same one the first associations are being developed.

If that is not possible, I only see two other options.  Number one is simply to hope that no one wants the bad publicity of invading and nuking a group of peaceful people.  Perhaps some resources can be devoted to PR, to encourage as many people to at least strongly oppose a nuclear response to associates, even if those people aren’t interested in becoming associates.

The other option is one that at least has a history of success, even if it’s not particularly appealing.  Specifically, I mean building or buying bombs of your own.  With a sufficiently large quantity of nuclear weapons, it is at least possible to ensure the death of the state (via the borderline/actual collapse of civilization).  Then, thanks to the inherently decentralized nature of associations, they will be able to rebuild on top of the proverbial ashes.

Somewhat of a change from MAD, as it’s only the destruction of the state which is assured.  Association as a way of life would most likely survive, even if that way of life would suck for a while.  If this could be convincingly argued to those nuclear powers, then the people in charge would have a greatly reduced incentive to attack.

This, combined with the strategies I offered elsewhere (like bribing the actual soldiers who maintain the weapons) will probably suffice to solve the “nuclear” problem, though fully developing the strategy should likely be a priority for the Foundation.

Anyway, now for a fun little problem for later.  It is self evident that, with sufficiently advanced automation, and sufficiently cheap energy, virtually any motivated party will be able to construct nuclear weapons.  There is not any particular reason to believe these levels of automation and energy technology will never be achieved, so eventually it will be necessary to account for this.

Hopefully, by the time this comes around, there simply won’t be anyone who wants to blow up the planet (they live here, after all), so maybe it won’t matter.  Still, that’ll be fun.  Good luck future people :D
