<<<
== Competing Gangs

I said I would address this earlier, though in truth it’s actually fairly similar to the army problem and is solved in a similar way.  Still, I’m too lazy to go back and edit my promise out, so I’ll spend some time covering it here.

To start, what is the Competing Gangs problem?  In short, it is the notion that under an anarchist system, the security firms would go to war with each other for customers, and the only way to constrain them would be to have a government, aka, the biggest gang imaginable.  I suppose, in some way, it does at least prevent the gangs from competing… much, because their conflicts are unimaginably devastating.  I can’t really say it does a good job a preventing a bunch of gangs from forming though, on accounts of that’s the system we’re using, and we’re chock full of gangs already.

Anyway, I’m digressing, back to the problem.  How do associations prevent competing “gangs” (aka, security firms) from going to war?  Easy, guards/soldiers need food, housing, money, etc. same as anyone, which are much harder to get if they don’t have standing.

I’ll explain with an example.  Let’s suppose Alice runs a security firm, and get’s the wild idea she should be empress of mankind.  To begin her ascension to the throne she instructs her employees to attack Bob’s security firm, her biggest competitor.  Let us further suppose her “soldiers” actually do so, and don’t all quit immediately.

Bob is very surprised by Alice’s attack on his headquarters, and has to escape from his offices via helicopter.  He immediately takes news of Alice’s attack to her association, and possibly straight to the PSA council as well.  Let us go ahead and assume all of Alice’s employees are in the same association, and it is controlled by Alice as well (to give her the best shot of this working).

Alice’s association is ejected from the PSA Council, along with all her employees, effectively making them all unassociated.

Now, after their first successful battle, her employees are very excited, and decide to celebrate by throwing a party.  One of them, Alex, is tasked with purchasing refreshments.  He travels to a store, makes his selection, and tries to check out.  His bank, not interested in working with someone unassociated (and also a member of the group of would be conquerers), declines the purchase.

Now, Alex may still be able to find some means to get his refreshments, but it has gotten far more difficult.

Meanwhile, the vast majority of Alice’s customers have decided not to do business with a group of unassociated people, because now they have no guarantee of service.  Alice has now lost most of her revenue, assuming she even has access to any of her finances at all.  This will make it difficult to continue purchasing supplies for her campaign, and also to compensate her employees for their time and risks.

Furthermore, all of Alice’s former customers likely still want the services of a security firm, so they now sign up with her competitors, increasing their revenue and making it easier for them to purchase supplies and hire new employees.

Speaking of new employees, Alice has a ton of them who currently are no longer getting paid, and struggle to function in society.  All her competitors will not have a terribly difficult time offering them a better deal.

Also, Alice has gone from being a legitimate security firm, to the head of a horde of rampaging barbarians.  Every remaining security firm can now attack her with impunity (for the purpose of self defense), destroying for good their former greatest competitor, and opening up a great deal of new market share.  They may also be able to secure some of her equipment and other assets, all the while never risking their own standing.

Assuming Alice survives the backlash, she’s gone from being one of the most powerful and influential people in society, to someone who will be lucky to work as a lunch lady in a secured association.  Not a great plan.
