<<<
== Standing Associations

A Standing Association is a kind of PSA which uses a combination of reputation and perks to secure good behavior from its members, and collects dues in order to generate revenue.  It could be described as a hybrid between an insurance company and a fraternity.  To illustrate how one might operate, consider the following example.

Alice is a member of Alpha Association, where she receives many benefits, such as insurance, access to exclusive clubs, counseling, coaching, and various other services, as well as Alpha’s guarantee to other parties (up to a substantial limit) that she will make good on her word.  In order to reach this level with them, Alice has spent several years working towards it, investing her time into the association to prove that she values her membership.  She has also agreed to maintain a certain standard of behavior.

Alice considers herself to be exceptionally lucky, and one day gets into an argument with Bob over it.  To prove just how blessed she is, she decides to show off how good she is with throwing knives at a local park.  To her great surprise, she misses the target entirely during her demonstration, and hits a bystander, Charlie, in the leg.

Charlie is, obviously, not pleased in the slightest by this.  For simplicity we will assume Charlie knows who Alice is, and what association she is in, so he goes to Alpha with a complaint.  Alice’s behavior was in clear violation of Alpha’s code of conduct, specifically where she generated a claim against them through obvious negligence.

There are several mechanisms by which Alice’s breach of standing can be resolved, although it can be assumed in all cases that Alpha will seek to maintain their revenue, and minimize their costs.  We will suppose in this example that Alpha settles with Charlie for medical bills, as well as some monetary compensation for his pain, suffering, and inconvenience, conditional upon Alice paying them back over some reasonable interval.  Alpha might also, either as part of their settlement with Charlie or independently, require Alice to participate in some program intended to reduce the likelihood of similar incidents happening in the future.

If Alice values her position in Alpha, and finds the terms to be reasonable, she is likely to comply.  If she rejects it, for whatever reason, then she will no longer receive the benefits of membership, which will make it difficult to live and work in society.  If we make the reasonable assumption that she enjoys participating in civilization, even if she leaves Alpha, she will likely join some other association.

It is unlikely this other association will be unaware of Alice’s prior behavior, especially because Alpha has a financial interest in informing them.  How they react will depend on the terms and nature of this association, but at the very least, Alpha will pursue Alice for her debt to them.  At this point the matter can either be handled by some procedure of the association, or can be taken to the  PSA Council for moderation.  In any case, Alice will not have escaped responsibility for her actions.

It is in fact likely that by leaving Alpha, Alice will have endured a far greater personal loss than she would have by simply staying with them, so this scenario is unlikely to occur regularly.  The most likely cause is actually that Alpha had unreasonable expectations on her, but an association that regularly mistreats its members is unlikely to endure for long.
