<<<
== Mediation

A mediator is anyone who is considered reasonably impartial and sufficiently knowledgeable on a given dispute that the parties involved will find their decision acceptable.  It is likely that most mediators will work for/be accredited by the PSA council, although it is entirely possible for an association to have internal mediators for disputes between members.  There is also nothing stopping someone from being a wholly independent mediator, except for the part where they need to be trusted by both parties (and their decision needs to be respected).

In general, though, I would consider mediators to largely handle disputes at the association v. association level, rather than concerning themselves with the affairs of individuals.  This is because of how their “mediation power” works, that is, it’s also purely associative.  The PSA Council “enforces” the decisions of its mediators by expelling from the council any association which refuses to accept a judgement.

Once expelled from a council, an association’s members would no longer be considered ‘associated’ (i.e. contracts cannot be enforced, much riskier to allow onto your property, possibly other stuff).  This would be a death sentence to any but the largest of associations (as its members would be very incentivized to switch to an association still in the Council), and even if an association was large enough to have a functional internal economy, it would still be a great hassle to its members, and would be vulnerable to having it’s customers poached with the promise better value.

In any case, it is to the PSA Council’s benefit (and likely to associates in general) for there to be only one PSA Council, so they should minimize any temptation to form a competitor.  It is also very unlikely for moderation to “get it right” the first time, every time.  Given this, a system of appeals would be valuable.  Although the design will ultimately come down to the PSA Council itself, my suggestion is to create a three tier system.  At the bottom are PSA Council accredited mediators, above them is the PSA Council itself (i.e. the group of people who run it), and finally it can be taken to the member associations.

The last stage could be done by vote, or as something like a jury, though I will propose a hybrid of the two.  The PSA will select (probably at random) some small number of member associations who vote for or against the judgement.  All the other member associations will be assumed to abstain, but may offer an aye or nay if they so choose.  If the judgement is rejected it would be kicked back down to a different mediator.  It might also be worth wile to allow the “jury” to offer their own judgement as well, which would then be an additional option to vote on.
