<<<
== Over/Under Lein

The Over/Under Lien is another concept not fundamental to associations, but which I feel could nevertheless be of some value.  It is another extension of an intuitive aspect of property rights, in this case of the notion that one doesn’t need any special permission to fly over some particular piece of property (so long as you are doing so in a manner that doesn’t disrupt or damage things down below).  Similarly, it is not considered trespassing to cross over an open field under most circumstances.

In fact, if someone were to shoot down an aircraft over their land they would be considered the aggressor (with perhaps some exceptions, though in all cases such a no-fly zone would have to be made explicitly and announced publicly).  This suggests that it is acceptable to generate an ad hoc lean on a property, at least temporarily.

The purpose of the Over/Under Lien is to capture this intuitive ‘right’ explicitly, and to expand it in such a way as to enable society to function without a lot of weird ambiguities.  This pairs especially well with the concept of Natural Flow, as there are a great many things which are unnatural flows, but are nevertheless considered highly valuable.  As an example, radio waves above a certain amplitude (and/or of certain wavelengths) are not at all natural phenomenon, but we might nevertheless consider the existence of cell phones to be of some value.

If we accept a right to natural flow, without also to an Over/Under Lien (or something similar), then any party who insisted could have faraday cages build around their property at the cellular operators expense (or at least greatly restrict the directions they can transmit).  This would likely make deploying such a technology untenable, and what’s more creates an incentive for firms to engage in obstructionist tactics against their competitors.

The Over/Under Lien is defined as a right to go over, under, or through someone else’s property without their permission, so long as such an action does not interfere with the owner’s legitimate use of it.  Legitimate use is, in this case, broadly defined as “anything they were doing with it before you generated your lien, or any ordinary use they could have for it at any time.”

As an example of how I intend it to be applied, consider a scenario where Alice is building an underground conduit for her power distribution service.  She has contacted everyone in some given neighborhood and gotten their permission, except Bob, who she was unable to locate (he’s currently vacationing in Antartica, and does not intend to return for several years).  It is not feasible for her to go around Bob’s property, nor is it to wait until the man in question is finally located.

As a matter of protocol, she registers her intent with the firm tracking land ownership in the area, then as a matter of safety (and consideration for Bob), ensures the route she’s chosen through Bob’s land does not contain any obstructions.  Afterwards, she drills underground through his land, and completes the project.

Let us further suppose that after Bob returns, he discovers this conduit and decides he doesn’t like it.  He files a dispute with Alice through the relevant mechanism in an attempt to force her to remove the conduit.  The arbiter would find that Alice had a legitimate lien for her conduit, and decide in her favor.  If Bob then went and dug out the conduit on his own, Alice would then have a valid grievance against him.

We can suppose a little further, and say that Bob argued Alice’s conduit interfered with his ability to farm his land, as his till would damage it when he passed over.  Given that Bob’s land was in a residential neighborhood, the arbiter would normally dismiss his claim, however, it Bob (or some authorized agent of his) was, in fact, currently farming the small patch of land (with allowances for the seasonal nature of such a thing), and the conduit would, in fact, interfere with that activity, then Alice could be forced to move her conduit, or else provide Bob some measure of compensation equivalent to the damage she did to Bob’s farming in that area.

It is worth noting that I expect such scenarios to actually be quite rare.

Here are a few other examples which I think will illustrate how I believe it should be applied (and perhaps some small measure of its value).

1) Building a road through a nature reserve.  So long as the project does not ruin the natural beauty (say by concealing the road with a line of trees), nor does it interfere in the migratory patterns of the wildlife (say by providing ample forest crossovers by tunneling/bridging), then it could be made, even if the owner of the reserve hated cars/transportation/humanity/etc. and could never be convinced to allow it.

2) While building a railroad for cargo transport, Alice’s firm is able to secure a route between two destinations (most likely via purchase), except for a thin but wide sliver of land held by Bob’s competing firm.  Bob is actively farming that land (or whatever) and refuses to allow Alice to complete her project.  Arbitration determines that, although Bob is clearly being an obstructionist, Alice is not allowed to build her railroad… on the surface.

Alice declares that she will simply tunnel well under Bob’s property, at some specific depth that will not interfere with Bob’s farming.  Bob attempts to obstruct Alice’s project further, by building a decorative underground wall, but Alice already generated her lien by a declaration of intent, and underground decorative walls are neither ordinary, nor were they a project Bob was undertaking at the time.  The arbiter decides in favor of Alice’s tunnel, and Bob now owns a bunch of farm land he doesn’t actually need or want.

3) Alice is building a cell tower on land that she owns, which is a well known project.  Bob believes radio waves summon evil ghosts, and should not be allowed to pass through his property.  He takes Alice to an arbiter, and is unable to prove radio waves summon evil ghosts.  Alice is permitted to build and operate her tower.
