<<<
== Actualized Damages

This is an idea which I am less confident in.  It may be valuable as is, or require some amount of work, or just be terrible.  The core idea is to treat actions nondeterministically, or put another way, to consider every possible consequence of an action when evaluating its impact, even though in reality only some limited subset of those consequences occurred.

As an example, suppose Alice is in a mall looking to buy a new hat.  While there she meets Bob, who, after the knife throwing incident, mocks her for her terrible luck.  Alice is so offended that she takes drastic action to prove her good fortune.  She takes a machine pistol from her belt (please do not assume this is intended to be a normal item to carry in a mall) and closes her eyes, then spins in a circle and fires wildly.

By some miracle, Alice successfully hit nothing of great value, and only managed to do a hundred dollars worth of damage to the walls.  Now, lucky she might be, but everyone in the mall is super pissed, and takes her to to an arbiter to answer for the harm she caused.  Alice argues that it was only a hundred dollars, which she can pay easily.  The advocates for the aggressed parties disagree, and demonstrate that, based on where and how many people were present, there was a one percent chance that she would have done one million dollars worth of damage.

If the arbiter uses the principle of actualized damage, he could take that one million dollars, multiply it by 0.01, and assign ten thousand dollars worth of damage to Alice, which would be distributed amongst the aggrieved parties.

The exact formulation of this principle might vary, and how the damages are calculated might as well, but I think it does capture the intuitive sense that risky behavior does represent a real harm to other parties, even if the actual consequences didn’t manifest in some particular incident.  Failing that, at the very least it serves as a deterrent to careless behavior.

It is worth noting that I would not consider actualized damage to be a replacement for real damage, but rather only a supplement.  Also, again, I am not certain this is a good idea, and I certainly wouldn’t consider it fundamental to association.
